### ISSUE TITLE
Improve Backend styling

### ISSUE THREAD

**Issue by danielduggin2** [UTCWeb/utctiny#24]
After implementing the Sleeky frontend and backend assets, we need to replace those logos with UTC logos.

**Comment by UTCGilligan** [comment]
- [ ] Fix header color and gap below logo on mobile view.
<img width="441" alt="Screenshot 2023-12-15 at 10 46 19" src="https://github.com/UTCWeb/utctiny/assets/49878588/28541e3d-554c-49fc-ae2d-7cb4940653af">
